language: node_js
node_js:
  - "6"
os:
  - linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - antlr4
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/build-debian.sh; fi
notifications:
  irc:
    channels:
      - "chat.freenode.net#jshdl"
