language: node_js
node_js:
  - "7"
os:
  - linux
sudo: required
cache:
  directories:
  - $HOME/antlr4
dist: trusty
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/build-debian.sh; fi
notifications:
  irc:
    channels:
      - "chat.freenode.net#jshdl"
